W0722 04:15:35.693000 1095487 site-packages/torch/distributed/run.py:766] 
W0722 04:15:35.693000 1095487 site-packages/torch/distributed/run.py:766] *****************************************
W0722 04:15:35.693000 1095487 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0722 04:15:35.693000 1095487 site-packages/torch/distributed/run.py:766] *****************************************
/home/liu/miniconda3/envs/GAIC/lib/python3.10/site-packages/open_clip/factory.py:388: UserWarning: These pretrained weights were trained with QuickGELU activation but the model config does not have that enabled. Consider using a model config with a "-quickgelu" suffix or enable with a flag.
  warnings.warn(
/home/liu/miniconda3/envs/GAIC/lib/python3.10/site-packages/open_clip/factory.py:388: UserWarning: These pretrained weights were trained with QuickGELU activation but the model config does not have that enabled. Consider using a model config with a "-quickgelu" suffix or enable with a flag.
  warnings.warn(
/home/liu/miniconda3/envs/GAIC/lib/python3.10/site-packages/open_clip/factory.py:388: UserWarning: These pretrained weights were trained with QuickGELU activation but the model config does not have that enabled. Consider using a model config with a "-quickgelu" suffix or enable with a flag.
  warnings.warn(
[Stage2] Loaded expert-0 weights from ckpts/npr/best_expert.pt
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/liu/miniconda3/envs/GAIC/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank1]:     return _run_code(code, main_globals, None,
[rank1]:   File "/home/liu/miniconda3/envs/GAIC/lib/python3.10/runpy.py", line 86, in _run_code
[rank1]:     exec(code, run_globals)
[rank1]:   File "/raid/dannyliu/GAI_Detection/GenAI_Detection/src/training/train_cvfid_stage2.py", line 217, in <module>
[rank1]:     train_fusion(args)
[rank1]:   File "/raid/dannyliu/GAI_Detection/GenAI_Detection/src/training/train_cvfid_stage2.py", line 99, in train_fusion
[rank1]:     load_expert_weights(model, [Path(args.ckpt_npr), Path(args.ckpt_dncnn), Path(args.ckpt_noiseprint)])
[rank1]:   File "/raid/dannyliu/GAI_Detection/GenAI_Detection/src/training/train_cvfid_stage2.py", line 50, in load_expert_weights
[rank1]:     ckpt = torch.load(ckpt_path, map_location="cpu")
[rank1]:   File "/home/liu/miniconda3/envs/GAIC/lib/python3.10/site-packages/torch/serialization.py", line 1479, in load
[rank1]:     with _open_file_like(f, "rb") as opened_file:
[rank1]:   File "/home/liu/miniconda3/envs/GAIC/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
[rank1]:     return _open_file(name_or_buffer, mode)
[rank1]:   File "/home/liu/miniconda3/envs/GAIC/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
[rank1]:     super().__init__(open(name, mode))
[rank1]: FileNotFoundError: [Errno 2] No such file or directory: 'ckpts/dncnn/best_expert.pt'
[Stage2] Loaded expert-0 weights from ckpts/npr/best_expert.pt
[Stage2] Loaded expert-0 weights from ckpts/npr/best_expert.pt
[rank2]: Traceback (most recent call last):
[rank2]:   File "/home/liu/miniconda3/envs/GAIC/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank2]:     return _run_code(code, main_globals, None,
[rank2]:   File "/home/liu/miniconda3/envs/GAIC/lib/python3.10/runpy.py", line 86, in _run_code
[rank2]:     exec(code, run_globals)
[rank2]:   File "/raid/dannyliu/GAI_Detection/GenAI_Detection/src/training/train_cvfid_stage2.py", line 217, in <module>
[rank2]:     train_fusion(args)
[rank2]:   File "/raid/dannyliu/GAI_Detection/GenAI_Detection/src/training/train_cvfid_stage2.py", line 99, in train_fusion
[rank2]:     load_expert_weights(model, [Path(args.ckpt_npr), Path(args.ckpt_dncnn), Path(args.ckpt_noiseprint)])
[rank2]:   File "/raid/dannyliu/GAI_Detection/GenAI_Detection/src/training/train_cvfid_stage2.py", line 50, in load_expert_weights
[rank2]:     ckpt = torch.load(ckpt_path, map_location="cpu")
[rank2]:   File "/home/liu/miniconda3/envs/GAIC/lib/python3.10/site-packages/torch/serialization.py", line 1479, in load
[rank2]:     with _open_file_like(f, "rb") as opened_file:
[rank2]:   File "/home/liu/miniconda3/envs/GAIC/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
[rank2]:     return _open_file(name_or_buffer, mode)
[rank2]:   File "/home/liu/miniconda3/envs/GAIC/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
[rank2]:     super().__init__(open(name, mode))
[rank2]: FileNotFoundError: [Errno 2] No such file or directory: 'ckpts/dncnn/best_expert.pt'
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/liu/miniconda3/envs/GAIC/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/home/liu/miniconda3/envs/GAIC/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/raid/dannyliu/GAI_Detection/GenAI_Detection/src/training/train_cvfid_stage2.py", line 217, in <module>
[rank0]:     train_fusion(args)
[rank0]:   File "/raid/dannyliu/GAI_Detection/GenAI_Detection/src/training/train_cvfid_stage2.py", line 99, in train_fusion
[rank0]:     load_expert_weights(model, [Path(args.ckpt_npr), Path(args.ckpt_dncnn), Path(args.ckpt_noiseprint)])
[rank0]:   File "/raid/dannyliu/GAI_Detection/GenAI_Detection/src/training/train_cvfid_stage2.py", line 50, in load_expert_weights
[rank0]:     ckpt = torch.load(ckpt_path, map_location="cpu")
[rank0]:   File "/home/liu/miniconda3/envs/GAIC/lib/python3.10/site-packages/torch/serialization.py", line 1479, in load
[rank0]:     with _open_file_like(f, "rb") as opened_file:
[rank0]:   File "/home/liu/miniconda3/envs/GAIC/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
[rank0]:     return _open_file(name_or_buffer, mode)
[rank0]:   File "/home/liu/miniconda3/envs/GAIC/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
[rank0]:     super().__init__(open(name, mode))
[rank0]: FileNotFoundError: [Errno 2] No such file or directory: 'ckpts/dncnn/best_expert.pt'
[rank0]:[W722 04:15:51.768620909 ProcessGroupNCCL.cpp:1476] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
W0722 04:15:52.736000 1095487 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 1095558 closing signal SIGTERM
W0722 04:15:52.736000 1095487 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 1095559 closing signal SIGTERM
E0722 04:15:53.301000 1095487 site-packages/torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 1) local_rank: 2 (pid: 1095560) of binary: /home/liu/miniconda3/envs/GAIC/bin/python3.10
Traceback (most recent call last):
  File "/home/liu/miniconda3/envs/GAIC/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/liu/miniconda3/envs/GAIC/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/home/liu/miniconda3/envs/GAIC/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/home/liu/miniconda3/envs/GAIC/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/home/liu/miniconda3/envs/GAIC/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/liu/miniconda3/envs/GAIC/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 270, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
src.training.train_cvfid_stage2 FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-07-22_04:15:52
  host      : DGX-Station-A100
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1095560)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
